[package]
name = "siderust-py"
version = "0.1.0"
edition = "2021"
description = "Python bindings for siderust astrometry and astrodynamics"
license = "AGPL-3.0"
repository = "https://github.com/Siderust/siderust-py"
authors = ["VPRamon <vallespuigramon@gmail.com>"]

[lib]
name = "siderust_py"
crate-type = ["cdylib", "rlib"]

[dependencies]
siderust = { version = "0.12", features = [] }
affn     = { version = "0.10", features = ["astro"] }
pyo3     = { version = "0.29" }

[dev-dependencies]
pyo3    = { version = "0.29", features = ["auto-initialize"] }
approx  = "0.5"
